server:
  error:
    include-message: ALWAYS

spring:
  datasource:
    url: jdbc:h2:file:~/jms-mock-h2

app:
  events:
    ping:
      enabled: true
      interval: PT15S

#logging.level.org.zalando.logbook: TRACE