name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1

      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: test-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
          restore-keys: |
            test-${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload service-jar
        uses: actions/upload-artifact@v2
        with:
          name: service-jar
          path: |
            backend/service/build/libs/jms-mock-*.jar
          retention-days: 7

  docker:
    runs-on: ubuntu-latest
    needs: [backend-build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Download service-jar
        uses: actions/download-artifact@v2
        with:
          name: service-jar
          path: backend/service/build/libs

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set tag
        run: echo "TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: backend/service
          file: backend/service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jms-mock:latest,${{ secrets.DOCKER_HUB_USERNAME }}/jms-mock:${{ env.TAG }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jms-mock-ui:latest,${{ secrets.DOCKER_HUB_USERNAME }}/jms-mock-ui:${{ env.TAG }}

  release-notes:
    runs-on: ubuntu-latest
    needs: [docker]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          configuration: ".github/release-changelog-builder.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download service-jar
        uses: actions/download-artifact@v2
        with:
          name: service-jar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          draft: true
          files: |
            jms-mock-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}